import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import styled from "@emotion/styled";
import icon from "../public/assets/img/menu.svg";
import Link from "next/link";
import Menu from "@/components/Menu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        
        <section className="menu">
          <Menu />
          <div>
            <p>●</p>
          </div>
        </section>
        <section>ok</section>
        <section id="two"></section>
        <section id="three"></section>
      </Container>
    </>
  );
}

const Container = styled.div`
  scroll-snap-type: y mandatory;
  overflow-y: scroll;
  height: 100vh;

  section {
    height: 100vh;
    scroll-snap-align: start;
  }

  
`;
